name = "later-url"
main = "src/index.js"
compatibility_date = "2023-12-19"

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Note: Use secrets to store sensitive data.
# Docs: https://developers.cloudflare.com/workers/platform/environment-variables
[vars]
MAX_COUNT = 593
PICK_RULE = { DAY_NUM = 4, ITEM_NUM = 4 }

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/runtime-apis/kv
[[kv_namespaces]]
binding = "LATER_URL"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
